name: shell-commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: display message
        run: echo "Hey there! I am Preetam"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: testing with python
        run: |
          import platform
          print (platform.processor())
        shell: python